language: php

php:
  - 7.4
  - 8.0

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install --no-interaction

script: bin/kahlan --coverage=3 --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    - secure: MgDiOLOg+oubbtqxljo7h+1BRitEecy2fBdeIPtOE5cUumEjLPijyKKRL1Dp4Hr2fcp0Q6OOdsBz8Csl3jL5AfVDCq0acg2U35s1FSafkAUNJ3LP79FM8CAOqarBOTcMu96Klpt2hqYAFbE4Qiy/Tmy6EgKs/Up8V5SD03t/K17ugj1g9fC3192/vm9nIXwQrJIf0Y4MjN87iSgY8QiH9b661Bs3PHj19w6R08cdPIotIoa5udGg3T/afENIFYoZ3EXp6KLOOyQnFYV2lu/lAV3c45yn3G0aO0QmzTjdLTq+Dza5GB3w3wN06MGhWigy1Ekrf4Xktld1DSzIz8XpYsuJUL0uaZMZOHOM7bdjj2s5Ny+F3R22NBoSHLXzWd3XkNNneR6WMmp4nMSXZQ90ESwA0xlaCay60MJiAZEbrCN2szSZomjq7D5gXbyza/g0sTaiuLeVZ0nNbBo+OJ1kxjc6tUCKXqtaagbggkjoEYL4LwFzy8tgtZtFlu3+yoNdYxHu18si1l/Xd/EAQLKMvtBiWqGxYbqA5Y2R+1qdZJaHUC8VjjVqFofBLpvflwcHWGiEK98duFHfJPlHOGrva8uRs0SPj5zxaHBwsnEtfkWaoUce4aop6Bcl7GoIPuGifSAJOpYxAZIUQuea6VVg2hNG3eNHyomUnHo3pzGhV08=
