language: php

php:
  - 7.4
  - 8.1

before_script:
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-interaction

script: bin/kahlan --coverage=3 --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    - secure: NPUsgzKDZEZuBI3oGa1V0KVKMSLoU5DKpXiHyUTIXdT2mWl8CE6b0e4RZiDvOqzZe3nRV3/H3JfmG1nrDkfuw355hozGycD08h4uiPmg1k57ud65SKCeNJciPKsuTpaMeKD/HjDMqnjsCAGZOn3k3EdDVrRHVU3zUnsk5Vt3+DaPLAM4nMqmnD1NuEyUpW2ZWkmH6OBg4AJeIhj2lp2SOYRjGTI3RhAgcXZ22Eqv0PEzh38zfDyrOccAMqpCwWpEa+CrEJQAccih1E4W7WR2kvLoUQZF9CfsXn4synRQeSZJinjGll9LGfaQFZHlioA6xU7p0xKs18yfNdXjtKm9Lfrki3TdbnL1g/SXZrVuJPwFiBG7oat7V2WMr6G5QoRvtUm5IvZbroEd9eMZs213VotQFkA1VGapjdAIyA11XN5g2Ja4dpTJnTca73Y8978qcnfZ9y+tQg/pU/FLY++TiTTMEH6VgGjpJHxNDA3nyGVc7ZcNMJa5OhDoBqD1Ip0QpQLDH6T0jJh8TLhJQfRKABLi4nmCCsJyqX5am1X8k0LmSoEdes2jp8rO+DAyB0/a2+S8yJH0kOiBz8KC4Dgmgmw5Oj90LTVF9DRLQRWiZtPoPhFjYgaXdSmR6s5HjAlflQujzafYKjJdkhlsb/39AhVEawV/3cwz0oDQ+Qf4Ac0=
